name: CachyOS kernel
on:
  push:
    branches:
      - main
    paths:
      - "**.nix"
      - .github/workflows/cachyos.yml

  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        architecture:
          - system: x86_64-linux
            runner: ubuntu-latest
          #- system: aarch64-linux
          #  runner: [ linux, ARM64, ktisis, ktisis-c4a-standard-4 ]
        channel:
          - nixos-24.11
          - nixos-unstable

    name: Build - ${{ matrix.channel }} - ${{ matrix.architecture.system }}
    runs-on: ${{ matrix.architecture.runner }}
    steps:
      - uses: actions/checkout@v4

      - uses: DeterminateSystems/nix-installer-action@v16
        with:
          source-url: https://install.lix.systems/lix/lix-installer-${{ matrix.architecture.system }}
          diagnostic-endpoint: ""

      - run: nix-channel --add https://nixos.org/channels/${{ matrix.channel }} nixos

      - uses: cachix/cachix-action@v15
        with:
          name: drakon64-nixos-cachyos-kernel
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - run: nix-build
